### ISSUE TITLE
Steige mit Condition Unserved werden laut GTFS-Germany-Feed bedient

### ISSUE THREAD

**Issue by hbruch** [mfdz/zhv-issues#14]
Für [9330 Haltestellen](https://github.com/mfdz/zhv-issues/files/6876617/stats_unserved_stops_but_served.csv) des zHV ist als condition `Unserved` angegeben, obwohl diese im aktuellen GTFS-Germany Datensatz mit stop_times angegeben sind. In einigen wenigen Fällen ist aus der Haltbeschreibung ersichtlich, dass es sich um Ersatzhaltestelllen handelt. Dies scheint jedoch nicht für die meisten anderen zu gelten.

**Stand der Daten** 
zHV: 09.07.2021
GTFS: 16.07.2021

**Comment by hbruch** [comment]
Die Zahl der als `Unserved` eingestuften, jedoch laut aktuellem GTFS-Datensatz bedienten Haltestellen steigt weiter an.
Derzeit beträgt sie 12626 und verteilt sich wie folgt auf die Bundesländer:

Führende Stellen DHID (entspricht Bundesland) | Anzahl Unserved trotz Bedienung laut GTFS
--|--
de:03|1841
de:05|1132
de:06|697
de:07|1987
de:08|2884
de:09|2803
de:13|1140
de:14|142

**Stand der Daten**
zHV: 07.03.2022
GTFS: 07.03.2022

**Comment by fahrplaner** [comment]
ggf. betriebliche Halte- oder Grenzhaltepunkte? Wobei diese im GTFS-Datensatz nicht enthalten sein dürften.
Bsp. Aachen Süd Grenze: de:05334:1204 , IBNR:8000403?

**Comment by hbruch** [comment]
Die Zahl der als Unserved eingestuften, jedoch laut aktuellem GTFS-Datensatz (Stand 19.12.2022) bedienten Haltestellen steigt weiter an.
Derzeit beträgt sie **17191** und verteilt sich wie folgt auf die Bundesländer:

Führende Stellen DHID (entspricht Bundesland) | Anzahl Unserved trotz Bedienung laut GTFS
-- | --
de:03|2356
de:05|1802
de:06|723
de:07|2256
de:08|3740
de:09|4603
de:10|1
de:13|1447
de:14|263

Statement:
```sql
SELECT SUBSTR(dhid,1,5), COUNT(*) 
  FROM zhv 
 WHERE condition='Unserved'  
   AND dhid IN (SELECT stop_id 
                  FROM gtfs_stop_times) 
 GROUP BY SUBSTR(dhid,1,5);
 ```

**Comment by CM-RMS** [comment]
Dieses und andere Felder sind nicht aktuell da sie nicht von allen Organisationen gepflegt werden - darauf weißen wir auch im Beipackzettel bei den zHV Daten, die auf der OpenDate Seite sehen hin. Deshalb werden solche Felder in naher Zukunft nicht mehr angezeigt werden und durch neue ersetzt.

**Comment by hbruch** [comment]
Danke für die zügige Antwort. Die Information, ob in Steig nicht mehr (oder noch nicht) bedient oder gegebenenfalls nur temporär durch einen anderen ersetzt wird (z.B. im Rahmen von Bauarbeiten), ist wäre sehr hilfreich. Ich freue mich auf die neuen, dann aussagekräftigeren Felder. Schöne Feiertage!

**Comment by hbruch** [comment]
Unter Hinzunahme des State 'OutOfOrder', dessen Bedeutung wir als 'stillgelegt' interpretieren, sind aktuell noch 432 Haltestellen im Widerspruch zu zHV-Angaben im DELFI-GTFS-Feed als stop_time referenziert:

Insbesondere der Kreis Rottweil im Verkehrsverbund Schwarzwald-Baar-Heuberg sticht hier mit knapp 400 Haltestellen heraus.

Die übrigen Haltestellen/Steige sind:
DHID | Name Station/Steig
-- | --
de:03151:2451|Ohof, Bahnhof Meinersen
de:03152:8277::1|Benterode Königstraße
de:03152:92842::1|Uschlag Am Kitzebach
de:03454:7035|Klostermoor,Brunz.Str/3Südwiek
de:05566:22109:0:2|2
de:05766:3703:1:2|Richtung Waldfriedhof
de:05911:5109:2:02|KOM Ri. Kleinherbeder Str.
de:05966:34586:1:2|Fi-Rönkhausen, Therecker Weg
de:05970:62448:1:1|Ri. Geisweid
de:07135:070187|Kaisersesch Verbandsgemeinde
de:07135:070209|Lutzerath Dauner Str.
de:07135:070325|Wollmerath Mitte
`de:08111:100:2:5`|Li 98 Rtg Asperger Str.
de:08117:7687|Weißenstein Friedhof
de:08212:6005:1:1|Gleis 1
de:08212:6005:2:2|Gleis 2
de:08212:801:1:12|Tram Gleis 12
de:08212:801:6:11|Tram Gleis 11
de:08235:10318:0:3|
de:08235:10401:0:3|
de:08235:10401:0:4|
de:08236:2817:0:1|
de:08236:5886:0:1|alle Richtungen
de:08311:30119:0:4|Bus Ri. Ost (in der Schillerstr.)
de:08311:30119:0:5|Bus Ri. West (in der Dreisamstr.)
de:08317:15813:1:2|Steig 2
de:08335:2262:0:13|STBUSB3
de:08337:74454|Rotzel Laufenburger Str.33
de:08425:2825:0:1|Alle Richtungen
de:09190:69661:0:2|WM Ludwig-Thoma-Straße, Mast 1
de:09279:81030|Haberskirchen, Edeka
de:13073:11020|Göhren
de:14523:904|Irfersgrün, Bf. Schulbushst.
de:14612:675:1:2|2
de:14625:7132:0:2|Richtung Bretnig-Hauswalde

**Comment by hbruch** [comment]
Mit der gleichen Begründung wie für #1 schließe ich diesen Eintrag, da nicht mehr relevant.
