### ISSUE TITLE
CSV und XML-Versionen in Datenportal vertauscht

### ISSUE THREAD

**Issue by hbruch** [mfdz/zhv-issues#19]
Die Datensätze der beiden Downloadseiten [deutschlandweite Haltestellendaten (XML)](https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-haltestellendaten-xml&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View) und [Deutschlandweite Haltestellendaten](https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-haltestellendaten&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View) sind anscheinend für den Datensatz des 4.7.2022 teilweise vertauscht.

Das CSV-Zip-File enthält den XML-Datensatz, der XML-Download das CSV.

Ich vermute als Fehlerquelle bei der mutmaßlich manuellen Zusammen-/Bereitstellung, die ggf. zukünftig durch eine Automatisierung vermieden werden könnte.

**Comment by CM-RMS** [comment]
Die zip-Files wurden korrigiert und neu auf die DODP gestellt. Wir werden prüfen ob es möglich ist das in Zukunft zu automatisieren.

**Comment by hbruch** [comment]
Danke. Ich schließe damit diesen Issue.
