### ISSUE TITLE
Fehlende Steige für Authority NVBW

### ISSUE THREAD

**Issue by hbruch** [mfdz/zhv-issues#20]
Der zHV-Datensatz vom 23.11.2022 enthält ca. 50.000 Steige weniger, als z.B. der Datensatz vom 31.10.2022.

Der Unterschied scheint im wesentlichen auf nicht enthaltene Steige der NVBW zurückzuführen zu sein.

```sh
$ grep "Q" zHV_aktuell_csv.2022-11-21.csv | wc
  417412 1041283 67091263
$ grep "Q" zHV_aktuell_csv.2022-10-31.csv | wc
  463727 1139557 74256405
$ grep "Q" zHV_aktuell_csv.2022-10-31.csv | grep NVBW | wc
   47025  100010 7246907
$ grep "Q" zHV_aktuell_csv.2022-11-21.csv | grep NVBW | wc
      22      54    3527
```

Wir bitte um Prüfung und Wiederherstellung.

Wir regen darüber hinaus an, dass bei solch frappierenden Mengenänderungen ein Hinweis in die beigefügten Beschreibungen aufgenommen wird. Wurde die Abweichung nicht durch DELFI detektiert, regen wir die Einrichtung eines Monitorings an.

**Comment by hbruch** [comment]
Der zHV-Datensatz vom 28.11.2022 enthält für die NVBW wieder Steige:

```sh
$ grep "Q" zHV_aktuell_csv.2022-11-28.csv | grep NVBW | wc
   47224   99985 7273527
```

Ich schließe diesen Issue, die o.g. Anregungen gelten unabhäging von diesem konkreten Issue.

**Comment by hbruch** [comment]
Im zHV-Datensatz vom 05.12.2022 fehlen erneut Steige, diesmal ca. 160.000.

```sh
$ grep '"Q"' zHV_aktuell_csv.2022-12-05.csv |  wc
  294318  682220 47208997
$ grep '"Q"' zHV_aktuell_csv.2022-12-05.csv | grep NVBW | wc
      0      57    3692
```

Ich bitte nochmals darum, bei solch gravierenden Mengenänderungen eine Erläuterung in die beigefügte Beschreibung aufzunehmen. Wurde die Abweichung nicht durch DELFI detektiert, sollte ein Monitorings eingerichtet werden.

**Comment by CM-RMS** [comment]
Hallo - wir haben das bereits an NVBW weitergegeben. Es gibt ein Projekt um im zHV weitere Qualitätskontrollen zu etablieren, aber das wird noch einige Zeit in Anspruch nehmen.

**Comment by NVBWSeifert** [comment]
> Hallo - wir haben das bereits an NVBW weitergegeben.

Hallo, können Sie an dietmar.seifert@nvbw.de mitteilen, wer bei der NVBW angesprochen wurde zum Thema?

vielen Dank und Grüße
Dietmar Seifert

**Comment by hbruch** [comment]
@CM-RMS Handelt es sich tatsächlich um ein Problem auf NVBW-Seite? Neben der NVBW sind auch für `VBB` und `BEG` keinerlei Steige in den Daten enthalten.

**Comment by hbruch** [comment]
Im Datensatz vom 12.12.2022 sind die Steige wieder enthalten. 

Die mitgelieferte Dokumentation `Beschreibung_ZHV-Datensatz_csv_20221212.pdf` gibt als Zahl der Masten (wir bezeichnen diese als Steige) jedoch weiterhin ca 416.400 an. Dieser Wert sollte periodisch angepasst werden und könnte auch als untere Grenze einer QS-Prüfung vor Veröffentlichung dienen.

**Comment by hbruch** [comment]
Im Datensatz vom 27.12.2022 fehlen erneut sämtliche Steige der NVBW.

Die Problemursache scheint weiterhin nicht an der Wurzel beseitigt. Wir bitten dringend um Ursachenanalyse und nachhaltige Beseitigung.

```sh
$ grep '"Q"' data/zHV_aktuell_csv.2022-12-27.csv | grep NVBW | wc
       0       0       0
```

**Comment by hbruch** [comment]
Der DELFI e.V. hat auf die Meldung hin einen erneuten Download aus dem zHV durchgeführt und die Veröffentlichung aktualisiert (Stand 30.12.2022). Der Datensatz enthält nun wieder die Steige des NVBW. (Vielen Dank!)

Ich schließe damit diesen Issue, auch wenn vermutlich weiterhin aufgrund sporadisch auftretender Fehler des Datenexports Steige nicht exportiert werden. Dies sollte jedoch vor Bereitstellung auf opendata-oepnv auffallen, so dass in einem solchen Fall die fehlerhaften Daten nicht veröffentlicht werden.
