### ISSUE TITLE
Fehlende Steigdaten in Baden-Württemberg

### ISSUE THREAD

**Issue by hbruch** [mfdz/zhv-issues#24]
Mit dem Datensatz vom 4.9.2023 fehlen für Baden-Württemberg bis auf in den durch den VRN bedienten Kreisen (`08128`, `08221`, `08222`, `08225`, `08226`) sämtliche Steigdaten:

```sh
$ grep de:08 zHV_aktuell_csv.2023-09-04.csv | grep '"Q"' | wc
    5287   12491  867159
$ grep de:08 zHV_aktuell_csv.2023-08-28.csv | grep '"Q"' | wc
   53739  116737 8439702
$ grep NVBW zHV_aktuell_csv.2023-08-28.csv | grep '"Q"' | wc
   49419  105618 7720117
$ grep NVBW zHV_aktuell_csv.2023-09-04.csv | grep '"Q"' | wc
       0       0       0
 ```

**Comment by CM-RMS** [comment]
Die Daten wurden neu auf die DODP gestellt

**Comment by hbruch** [comment]
Danke. Damit sind nun wieder 472428 Steige (genau genommen Zeilen mit "Q") im Datensatz `zHV_aktuell_csv.2023-09-05.csv` enthalten.
